stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
      - outputs/raw/
  tokenize_data:
    cmd: python src/tokenize_data.py
    deps:
    - src/tokenize_data.py
